language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq unoconv tidy
# command to install dependencies
install:
  - python setup.py dev
  - oooctl restart
# command to run tests
script: "python setup.py test"
